server:
    port: 8084

zuul:
  routes:
    oauth:
      path: /oauth/**
      url: http://localhost:8081/spring-security-oauth-server/oauth
    foos:
      path: /api/**
      url: http://localhost:8082/spring-security-oauth-resource/
 
  Servlet30WrapperFilter.pre.disable: true