oauth-db:
  image: mysql:5.7.18
  container_name: oauth-db
  command: mysqld --user=root --verbose
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: oauth
    MYSQL_USER: test
    MYSQL_PASSWORD: test
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ALLOW_EMPTY_PASSWORD: "true"
