spring.cloud.config.server.git.uri=https://raw.githubusercontent.com/labcabrera/lab-oauth2/master/config/authserver/application.yml
#server:
#  port: 9999
#  contextPath: /uaa
#security:
#  user:
#    password: password
#logging:
#  level:
#    org.springframework.security: DEBUG
#
#app:
#  security:
#    keystore:
#      file: keystore.jks
#      password: foobar
#      key: test
#